service: jenkins-lambda-handler

provider:
  name: aws
  versionFunctions: false
  logRetentionInDays: 7
  region: eu-central-1
  endpointType: REGIONAL
  stage: dev
  profile: serverless-admin-profile
  tags:
    application: "jenkins-lambda"
    owner: "serverless"
  stackTags:
    application: "jenkins-lambda"
    owner: "serverless"
  deploymentBucket:
    blockPublicAccess: true
    tags:
      application: "jenkins-lambda"
      owner: "serverless"

custom:
  topicName: github-webhook-events

functions:
  Handler:
    name: jenkins-lambda-handler
    image: 671123374425.dkr.ecr.eu-central-1.amazonaws.com/jenkins-lambda/handler:latest
    role: HandlerRole
    architecture: x86_64
    memorySize: 2048
    timeout: 900
    events:
      - sns:
          arn: !ImportValue WebhookEventsTopicArn
          topicName: ${self:custom.topicName} # it seems serverless framework cannot accept an !ImportValue here

resources:
  Resources:
    HandlerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: jenkins-lambda-handler-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: jenkins-lambda-handler
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
        Tags:
          - Key: application
            Value: jenkins-lambda
          - Key: owner
            Value: serverless
